trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.5.7'

- task: AzureCLI@2
  displayName: 'Terraform Deploy'
  inputs:
    azureSubscription: 'devops 1'   # Your Service Connection name
    scriptType: bash
    scriptLocation: inlineScript
    workingDirectory: terraform-azure
    inlineScript: |
      terraform init
      terraform validate
      terraform plan
      terraform apply -auto-approve